FROM 607756570330.dkr.ecr.eu-west-1.amazonaws.com/dmn-php:php80-ac819d7

WORKDIR /opt

RUN apk add --no-cache libpng libpng-dev && docker-php-ext-install gd && apk del libpng-dev

RUN docker-php-ext-install pcntl

COPY composer.json /opt
COPY composer.lock /opt
