FROM php:cli-alpine3.15

COPY --from=composer:2.0.13 /usr/bin/composer /usr/bin/composer

WORKDIR /opt

RUN apk add --update --no-cache libpng libpng-dev && apk del libpng-dev

RUN apk add php8-gd php8-pcntl

COPY composer.json /opt
COPY composer.lock /opt
RUN composer update
