FROM 607756570330.dkr.ecr.eu-west-1.amazonaws.com/dmn-php:php80-ac819d7

WORKDIR /opt

RUN apk add --update --no-cache libpng libpng-dev && apk del libpng-dev

RUN apk add php8-gd php8-pcntl

COPY composer.json /opt
COPY composer.lock /opt
RUN composer update
